export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_SUCCESS_MSG="AUTH_SUCCESS_MSG"
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_FAILURE="AUTH_FAILURE"
export const AUTH_LOGOUT_SUCCESS="AUTH_LOGOUT_SUCCESS"

export const GET_SINGLE_USER_DATA="GET_SINGLE_USER_DATA"

export const PRODUCT_FAILURE="PRODUCT_FAILURE"
export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_ORGANIZER="SINGLE_PRODUCT_ORGANIZER"
export const SINGLE_PRODUCT_PAYMENT="SINGLE_PRODUCT_PAYMENT"